### PR TITLE
Adding pagination config

### PR DESCRIPTION
**Pull request by nsiwnf**
Does this look ok?

Screen Shot 2020-02-27 at 8 29 03 AM

Screen Shot 2020-02-27 at 8 38 39 AM

### CODE REVIEW

**Comment by chrisluedtke** [comment]
I prefer sticking with the theme defaults which you can find here: https://bootswatch.com/darkly/

```html
<div>
  <ul class="pagination">
    <li class="page-item disabled">
      <a class="page-link" href="#">&laquo;</a>
    </li>
    <li class="page-item active">
      <a class="page-link" href="#">1</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">2</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">3</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">4</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">5</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">&raquo;</a>
    </li>
  </ul>
</div>
```

**Comment by nsiwnf** [comment]
Yeah, I guess it’s ready if this is a better state than the current- I dont know jekyll well enough to Get the arrows to go to the first and last page and the first page looks like it’s just the homepage —> might be nice to have a “preview” of the most recent, then a “see more” and paginate that portion?

**Comment by chrisluedtke** [comment]
@nsiwnf I updated to display all paginated links
image

One improvement from here would be to implement a max number to display, then have the last number link be a link to the last paginated page.

**Comment by nsiwnf** [comment]
Thanks for pushing those changes!
We can add our own CSS, right? It wouldnt be too customized

Screen Shot 2020-02-27 at 10 06 58 PM

**Pull request merged**
